-- Fictional providers and demo prices; no real reservations are issued.
-- Flights (price per traveler, daily seats)
INSERT INTO services (category, name, provider_name, city, description, unit_price_minor, price_unit, booking_fee_minor, daily_capacity, rating, attributes, free_cancel_hours, late_refund_percent) VALUES
  ('flight', 'Madrid to Barcelona morning flight', 'Costa Air (demo)', 'Barcelona', 'Direct economy flight with one cabin bag.', 6900, 'per_traveler', 300, 40, 4.3, '{"origin": "Madrid", "destination": "Barcelona", "departureTime": "08:15", "durationMin": 80, "baggage": "1 cabin bag"}', 48, 0),
  ('flight', 'Lisbon to Barcelona midday flight', 'Mediterra Airways (demo)', 'Barcelona', 'Direct flight, seat selection included.', 11900, 'per_traveler', 300, 30, 4.5, '{"origin": "Lisbon", "destination": "Barcelona", "departureTime": "11:40", "durationMin": 125, "baggage": "1 cabin bag + 1 checked bag"}', NULL, 0),
  ('flight', 'Rome to Barcelona early saver', 'Costa Air (demo)', 'Barcelona', 'Lowest fare, small personal item only.', 4900, 'per_traveler', 300, 50, 3.8, '{"origin": "Rome", "destination": "Barcelona", "departureTime": "06:50", "durationMin": 115, "baggage": "Personal item"}', NULL, 0),
  ('flight', 'Barcelona to Palma evening hop', 'Mediterra Airways (demo)', 'Barcelona', 'Short island flight to Mallorca.', 5900, 'per_traveler', 300, 35, 4.2, '{"origin": "Barcelona", "destination": "Palma", "departureTime": "17:30", "durationMin": 55, "baggage": "1 cabin bag"}', 24, 50);

-- Trains
INSERT INTO services (category, name, provider_name, city, description, unit_price_minor, price_unit, booking_fee_minor, daily_capacity, rating, attributes, free_cancel_hours, late_refund_percent) VALUES
  ('train', 'Madrid to Barcelona high-speed train', 'Peninsula Rail (demo)', 'Barcelona', 'High-speed service with reserved seat.', 6500, 'per_traveler', 0, 80, 4.6, '{"origin": "Madrid", "destination": "Barcelona", "departureTime": "09:00", "durationMin": 150, "seatClass": "Standard"}', 24, 50),
  ('train', 'Madrid to Barcelona low-cost train', 'Litoral Express (demo)', 'Barcelona', 'Budget high-speed train, no changes allowed.', 3500, 'per_traveler', 0, 120, 4.0, '{"origin": "Madrid", "destination": "Barcelona", "departureTime": "13:05", "durationMin": 165, "seatClass": "Standard"}', NULL, 0),
  ('train', 'Valencia to Barcelona coastal train', 'Litoral Express (demo)', 'Barcelona', 'Scenic route along the Mediterranean coast.', 3900, 'per_traveler', 0, 90, 4.4, '{"origin": "Valencia", "destination": "Barcelona", "departureTime": "10:20", "durationMin": 180, "seatClass": "Comfort"}', 48, 30),
  ('train', 'Paris to Barcelona direct train', 'Peninsula Rail (demo)', 'Barcelona', 'Cross-border direct high-speed train.', 9900, 'per_traveler', 0, 60, 4.7, '{"origin": "Paris", "destination": "Barcelona", "departureTime": "10:07", "durationMin": 395, "seatClass": "Standard"}', 72, 50);

-- Ferries
INSERT INTO services (category, name, provider_name, city, description, unit_price_minor, price_unit, booking_fee_minor, daily_capacity, rating, attributes, free_cancel_hours, late_refund_percent) VALUES
  ('ferry', 'Barcelona to Palma overnight ferry', 'Baleares Sea Lines (demo)', 'Barcelona', 'Overnight crossing with reclining seat.', 5500, 'per_traveler', 200, 150, 4.1, '{"origin": "Barcelona", "destination": "Palma", "departureTime": "23:00", "durationMin": 450, "seatClass": "Reclining seat"}', 48, 25),
  ('ferry', 'Barcelona to Ibiza evening ferry', 'Blue Strait Ferries (demo)', 'Barcelona', 'Evening sailing to Ibiza town.', 6200, 'per_traveler', 200, 120, 4.0, '{"origin": "Barcelona", "destination": "Ibiza", "departureTime": "21:30", "durationMin": 540, "seatClass": "Standard seat"}', 24, 0),
  ('ferry', 'Barcelona to Genoa ferry', 'Blue Strait Ferries (demo)', 'Barcelona', 'Long crossing to Italy, non-refundable fare.', 8900, 'per_traveler', 200, 100, 3.9, '{"origin": "Barcelona", "destination": "Genoa", "departureTime": "20:30", "durationMin": 1140, "seatClass": "Standard seat"}', NULL, 0);

-- Hotels (price per room per night, daily rooms available, tourist tax per guest per night)
INSERT INTO services (category, name, provider_name, city, description, unit_price_minor, price_unit, booking_fee_minor, daily_capacity, rating, attributes, free_cancel_hours, late_refund_percent) VALUES
  ('hotel', 'Casa Gothic Boutique Hotel', 'Casa Gothic (demo)', 'Barcelona', 'Boutique rooms in the Gothic Quarter, breakfast included.', 14500, 'per_room_night', 0, 8, 4.7, '{"stars": 4, "maxGuestsPerRoom": 2, "neighborhood": "Gothic Quarter", "checkInTime": "15:00", "touristTaxPerGuestNightMinor": 375, "amenities": ["Breakfast", "Wi-Fi", "Air conditioning"]}', 48, 0),
  ('hotel', 'Eixample Design Rooms', 'Eixample Rooms (demo)', 'Barcelona', 'Modern rooms close to Passeig de Gracia.', 9800, 'per_room_night', 0, 12, 4.4, '{"stars": 3, "maxGuestsPerRoom": 3, "neighborhood": "Eixample", "checkInTime": "14:00", "touristTaxPerGuestNightMinor": 275, "amenities": ["Wi-Fi", "Family rooms"]}', 24, 50),
  ('hotel', 'Barceloneta Beach Hostel', 'Beach Hostels (demo)', 'Barcelona', 'Simple private rooms a short walk from the beach.', 4200, 'per_room_night', 0, 20, 3.9, '{"stars": 2, "maxGuestsPerRoom": 4, "neighborhood": "Barceloneta", "checkInTime": "14:00", "touristTaxPerGuestNightMinor": 125, "amenities": ["Shared kitchen", "Wi-Fi"]}', NULL, 0),
  ('hotel', 'Montjuic Garden Suites', 'Garden Suites (demo)', 'Barcelona', 'Spacious suites with garden views and spa access.', 26500, 'per_room_night', 0, 5, 4.9, '{"stars": 5, "maxGuestsPerRoom": 2, "neighborhood": "Montjuic", "checkInTime": "15:00", "touristTaxPerGuestNightMinor": 500, "amenities": ["Spa", "Pool", "Breakfast", "Wi-Fi"]}', 72, 25);

-- eSIM packages (price per eSIM, no daily limit)
INSERT INTO services (category, name, provider_name, city, description, unit_price_minor, price_unit, booking_fee_minor, daily_capacity, rating, attributes, free_cancel_hours, late_refund_percent) VALUES
  ('esim', 'Spain 5 GB for 7 days', 'RoamLite (demo)', 'Barcelona', 'Data-only eSIM for Spain.', 799, 'per_item', 0, NULL, 4.2, '{"coverage": "Spain", "dataGb": 5, "validityDays": 7}', 24, 0),
  ('esim', 'Spain 20 GB for 30 days', 'RoamLite (demo)', 'Barcelona', 'Data-only eSIM for longer stays in Spain.', 1999, 'per_item', 0, NULL, 4.4, '{"coverage": "Spain", "dataGb": 20, "validityDays": 30}', 24, 0),
  ('esim', 'Europe 10 GB for 15 days', 'EuroConnect (demo)', 'Barcelona', 'Works in 30+ European countries.', 1499, 'per_item', 0, NULL, 4.5, '{"coverage": "Europe", "dataGb": 10, "validityDays": 15}', 24, 0),
  ('esim', 'Europe unlimited for 30 days', 'EuroConnect (demo)', 'Barcelona', 'Unlimited data with fair-use policy.', 3999, 'per_item', 0, NULL, 4.1, '{"coverage": "Europe", "dataGb": null, "validityDays": 30}', NULL, 0);

-- City transport and airport transfers
INSERT INTO services (category, name, provider_name, city, description, unit_price_minor, price_unit, booking_fee_minor, daily_capacity, rating, attributes, free_cancel_hours, late_refund_percent) VALUES
  ('transfer', 'Airport to city private car', 'CityRide (demo)', 'Barcelona', 'Private car for up to 3 passengers with meet and greet.', 3900, 'per_vehicle', 0, 15, 4.6, '{"origin": "Barcelona Airport (BCN)", "destination": "City centre", "vehicleCapacity": 3, "transferType": "Airport transfer", "pickupTime": "12:00"}', 24, 0),
  ('transfer', 'Airport to city private minivan', 'CityRide (demo)', 'Barcelona', 'Minivan for groups up to 7 passengers.', 6500, 'per_vehicle', 0, 6, 4.5, '{"origin": "Barcelona Airport (BCN)", "destination": "City centre", "vehicleCapacity": 7, "transferType": "Airport transfer", "pickupTime": "12:00"}', 24, 0),
  ('transfer', 'Airport shuttle bus', 'AeroShuttle (demo)', 'Barcelona', 'Shared shuttle every 10 minutes.', 690, 'per_traveler', 0, 200, 4.0, '{"origin": "Barcelona Airport (BCN)", "destination": "Placa Catalunya", "transferType": "Shared shuttle"}', 2, 0),
  ('transfer', 'Barcelona 48-hour city transport pass', 'Metro Pass Office (demo)', 'Barcelona', 'Unlimited metro, bus, and tram rides for 48 hours.', 1750, 'per_traveler', 0, NULL, 4.3, '{"origin": "Any city station", "destination": "Zone 1", "transferType": "City transport pass", "validityHours": 48}', 24, 0),
  ('transfer', 'Cruise port to city taxi', 'CityRide (demo)', 'Barcelona', 'Pre-booked taxi from the cruise terminal.', 2800, 'per_vehicle', 0, 10, 4.2, '{"origin": "Barcelona Cruise Port", "destination": "City centre", "vehicleCapacity": 4, "transferType": "Port transfer", "pickupTime": "09:00"}', 12, 0);

-- Activities and event tickets (price per ticket, daily tickets)
INSERT INTO services (category, name, provider_name, city, description, unit_price_minor, price_unit, booking_fee_minor, daily_capacity, rating, attributes, free_cancel_hours, late_refund_percent) VALUES
  ('activity', 'Sagrada Familia guided tour', 'Barcelona Walks (demo)', 'Barcelona', 'Skip-the-line guided basilica tour.', 3900, 'per_ticket', 150, 30, 4.8, '{"startTime": "10:00", "durationMin": 90, "meetingPoint": "Placa de la Sagrada Familia", "ticketType": "Guided tour"}', 24, 0),
  ('activity', 'Gothic Quarter walking tour', 'Barcelona Walks (demo)', 'Barcelona', 'History walk through medieval streets.', 1800, 'per_ticket', 0, 25, 4.6, '{"startTime": "16:00", "durationMin": 120, "meetingPoint": "Barcelona Cathedral steps", "ticketType": "Walking tour"}', 24, 50),
  ('activity', 'Flamenco night show', 'Tablao Nights (demo)', 'Barcelona', 'Live flamenco event with one drink.', 4500, 'per_ticket', 150, 60, 4.7, '{"startTime": "21:00", "durationMin": 75, "meetingPoint": "Las Ramblas venue", "ticketType": "Event ticket"}', NULL, 0),
  ('activity', 'Park Guell entry ticket', 'City Monuments (demo)', 'Barcelona', 'Timed entry to the monumental zone.', 1800, 'per_ticket', 0, 100, 4.4, '{"startTime": "09:30", "durationMin": 120, "meetingPoint": "Park Guell main gate", "ticketType": "Entry ticket"}', NULL, 0),
  ('activity', 'Sunset catamaran cruise', 'Sea Breeze Tours (demo)', 'Barcelona', 'Two-hour cruise with live music.', 5500, 'per_ticket', 150, 20, 4.5, '{"startTime": "19:00", "durationMin": 120, "meetingPoint": "Port Vell pier 3", "ticketType": "Cruise"}', 48, 25);
